export const LAYOUT_CONFIG = {
  OVERVIEW_MAX_RATIO: 0.4,
  CONTENT_MIN_RATIO: 0.6,
  EXPLORER_WIDTH: 280,
  COMPACT_CARD_MIN_WIDTH: 120,
  COMPACT_CARD_MAX_WIDTH: 180,
  MIN_PAGE_HEIGHT: 500,
  OVERVIEW_MIN_HEIGHT: 180
} as const
